<!DOCTYPE html>
<html lang="en-US">
	<head>
		<meta charset="utf-8">
			<title>HELP</title>
			<link rel="stylesheet" href="">
			<!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
			<!--[if lt IE 9]>
				<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
			<![endif]-->
	</head>
	
	<body>
		<h1>HELP</h1>
		<p>This page was generated by the <code>home</code> controller and the method <code>help</code>.</p>
		<p>The view does exists at <code>app/views/home/help.php</code></p>
	</body>
	
</html>